### ISSUE TITLE
To Do List before Wednesday Meeting at 2:30 

### ISSUE THREAD

**Issue by michkatz** [michkatz/xrdos#1]
**ML Toolkits to Look at (choose one to look at closely)**
RYAN: SciKitLearn, Pybrain
ANDREW: Cafe, Deap 
COREY: Keras, TensorFlow, Theanos

**Other stuff to do**
MICHELLE: Make Software Design file
ANDREW: Read paper on Slack

**Comment by copsea** [comment]
Notes: 
Caffe is coded in C++. That means it's higher performing than python code but might add a layer of ambiguity between us and the algorithms(not that that's a big issue because we already don't know shit). Supposed to be super fast. From reading about Deap, it mostly supports genetic algorithms which are slightly different from neural networks and I don't think it's what we want, so I think we should stay away from Deap.

**Comment by ryancarlin0331** [comment]
Pybrain:
-Good for beginners
-Neural networks, unsupervised
-Free and seems useful
-GitHub last commit late 2017
-120/43 open/close
-Really detailed documentation

SciKitLearn
-Used in class
-Seems to specialize in linear models
-Way more information exists, a ton of documentation, examples, support
-1225/4682 open/close
-incorporates with numpy and spicy

Tbh both are probably helpful and sklearn is crazy popular. Pybrain is less popular but really throws around "neural networks" in its documentation and testimonials. I spent a lot more time with Pybrain and I think we should include this for the technology review but it does seem more dated and will likely come with a steeper learning curve.
